# Site settings
title: Business Analyst Irina Gankova
description: Explore the professional journey of Irina Gankova, an experienced Business Analyst with over 5 years of expertise in software development. Passionate about solving complex problems, Irina specializes in systematization, management, and innovative solutions using BA techniques. Active in the business analysis community, she shares knowledge and mentors others while staying updated on the latest trends. Connect with Irina for collaborations and opportunities.

# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Irina Gankova
user_expertise: Expertise
user_description: I believe in learning throughout life and enjoy solving important problems with technology. This passion led me to become a Business Analyst in Software Development and a mentor for others. I find it rewarding to discover patterns and create solutions to reach goals.
  <br><br> With over 5 years of experience as a Business Analyst, I focus on continuous improvement. I stay updated on new trends and technologies to ensure my solutions are creative and effective.

user_title: Business Analyst
email: Irisgankova@gmail.com
linkedin: https://www.linkedin.com/in/irinagankova

# Google-analytics
google-analytics:
  id: ""

exclude: [ 'package.json', 'src' , 'node_modules' ]
